### ISSUE TITLE
这个报错不知道是什么问题

### ISSUE THREAD

**Issue by tohere** [echo008/wxss-cli#3]
你好，不知道这个是什么问题
      throw er; // Unhandled 'error' event
      ^
Error: EPERM: operation not permitted, watch '\Documents and Settings'
    at FSWatcher.start (internal/fs/watchers.js:165:26)
    at Object.watch (fs.js:1251:11)

**Comment by tohere** [comment]
已经解决了，我指定一个确定的less文件就可以运行了
